const data = {
  pant: [
    {
      name: 'deep slim shirt',
      slug: 'deep-slim-shrt',
      category: 'pant',
      image: '/images/pant/pant1.jpeg',
      price: 100,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'nike1 slim shirt',
      slug: 'nike1-slim-shrt',
      category: 'pant',
      image: '/images/pant/pant2.jpeg',
      price: 120,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'addidas-slim shirt',
      slug: 'addidas-slim-shrt',
      category: 'pant',
      image: '/images/pant/pant3.jpeg',
      price: 120,
      CountInStock: 10,
      brand: 'addidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'zara-slim shirt',
      slug: 'zara-slim-shrt',
      category: 'pant',
      image: '/images/pant/pant4.jpeg',
      price: 120,
      CountInStock: 10,
      brand: 'zara',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'nova-slim shirt',
      slug: 'nova-slim-shrt',
      category: 'pant',
      image: '/images/pant/pant5.jpeg',
      price: 120,
      CountInStock: 10,
      brand: 'nova',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep slim shirt',
      slug: 'deep1-slim-shrt',
      category: 'pant',
      image: '/images/pant/pant6.jpeg',
      price: 100,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'nike1 slim shirt',
      slug: '1nike1-slim-shrt',
      category: 'pant',
      image: '/images/pant/pant7.jpeg',
      price: 120,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'addidas-slim shirt',
      slug: 'addidas1-slim-shrt',
      category: 'pant',
      image: '/images/pant/pant8.jpeg',
      price: 120,
      CountInStock: 10,
      brand: 'addidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'zara-slim shirt',
      slug: 'zara1-slim-shrt',
      category: 'pant',
      image: '/images/pant/pant9.jpeg',
      price: 120,
      CountInStock: 10,
      brand: 'zara',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'nova-slim shirt',
      slug: 'nova1-slim-shrt',
      category: 'pant',
      image: '/images/pant/pant10.jpeg',
      price: 120,
      CountInStock: 10,
      brand: 'nova',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
  ],
  shirt: [
    {
      name: 'deep slim shirt',
      slug: 'deep-slim-shrt',
      category: 'shirt',
      image: '/images/shirt/shirt1.jpeg',
      price: 100,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep slim shirt',
      slug: 'deep2-slim-shrt',
      category: 'shirt',
      image: '/images/shirt/shirt2.jpeg',
      price: 100,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep slim shirt',
      slug: 'deep3-slim-shrt',
      category: 'shirt',
      image: '/images/shirt/shirt3.jpeg',
      price: 100,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep slim shirt',
      slug: 'deep4-slim-shrt',
      category: 'shirt',
      image: '/images/shirt/shirt4.jpeg',
      price: 100,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep slim shirt',
      slug: 'deep5-slim-shrt',
      category: 'shirt',
      image: '/images/shirt/shirt5.jpeg',
      price: 100,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep slim shirt',
      slug: 'deep6-slim-shrt',
      category: 'shirt',
      image: '/images/shirt/shirt6.jpeg',
      price: 100,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep slim shirt',
      slug: 'deep7-slim-shrt',
      category: 'shirt',
      image: '/images/shirt/shirt7.jpeg',
      price: 100,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep slim shirt',
      slug: 'deep8-slim-shrt',
      category: 'shirt',
      image: '/images/shirt/shirt8.jpeg',
      price: 100,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep slim shirt',
      slug: 'deep9-slim-shrt',
      category: 'shirt',
      image: '/images/shirt/shirt9.jpeg',
      price: 100,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep slim shirt',
      slug: 'deep10-slim-shrt',
      category: 'shirt',
      image: '/images/shirt/shirt10.jpeg',
      price: 100,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
  ],
  tshirt: [
    {
      name: 'deep slim tshirt',
      slug: 'deep-slim-tshrt',
      category: 'tshirt',
      image: '/images/tshirt/tshirt1.jpeg',
      price: 100,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep slim tshirt',
      slug: 'deep2-slim-tshrt',
      category: 'tshirt',
      image: '/images/tshirt/tshirt2.jpeg',
      price: 100,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep slim tshirt',
      slug: 'deep3-slim-tshrt',
      category: 'tshirt',
      image: '/images/tshirt/tshirt3.jpeg',
      price: 100,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep slim tshirt',
      slug: 'deep4-slim-tshrt',
      category: 'tshirt',
      image: '/images/tshirt/tshirt4.jpeg',
      price: 100,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep slim tshirt',
      slug: 'deep5-slim-tshrt',
      category: 'tshirt',
      image: '/images/tshirt/tshirt5.jpeg',
      price: 100,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep slim tshirt',
      slug: 'deep6-slim-tshrt',
      category: 'tshirt',
      image: '/images/tshirt/tshirt6.jpeg',
      price: 100,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep slim tshirt',
      slug: 'deep7-slim-tshrt',
      category: 'tshirt',
      image: '/images/tshirt/tshirt7.jpeg',
      price: 100,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep slim tshirt',
      slug: 'deep8-slim-tshrt',
      category: 'tshirt',
      image: '/images/tshirt/tshirt8.jpeg',
      price: 100,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep slim tshirt',
      slug: 'deep9-slim-tshrt',
      category: 'tshirt',
      image: '/images/tshirt/tshirt9.jpeg',
      price: 100,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep slim tshirt',
      slug: 'deep10-slim-tshrt',
      category: 'tshirt',
      image: '/images/tshirt/tshirt10.jpeg',
      price: 100,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
  ],
  shoes: [
    {
      name: 'deep  shoes',
      slug: 'deep-slim-shoes',
      category: 'shoes',
      image: '/images/shoes/shoes1.jpeg',
      price: 600,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep2  shoes',
      slug: 'deep2-slim-shoes',
      category: 'shoes',
      image: '/images/shoes/shoes2.jpeg',
      price: 800,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep3  shoes',
      slug: 'deep3-slim-shoes',
      category: 'shoes',
      image: '/images/shoes/shoes3.jpeg',
      price: 300,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep4  shoes',
      slug: 'deep4-slim-shoes',
      category: 'shoes',
      image: '/images/shoes/shoes4.jpeg',
      price: 700,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep5 shoes',
      slug: 'deep5-slim-shoes',
      category: 'shoes',
      image: '/images/shoes/shoes5.jpeg',
      price: 500,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep6 shoes',
      slug: 'deep6-slim-shoes',
      category: 'shoes',
      image: '/images/shoes/shoes6.jpeg',
      price: 3400,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep7 shoes',
      slug: 'deep7-slim-shoes',
      category: 'shoes',
      image: '/images/shoes/shoes7.jpeg',
      price: 600,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep8 shoes',
      slug: 'deep8-slim-shoes',
      category: 'shoes',
      image: '/images/shoes/shoes8.jpeg',
      price: 800,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep9 shoes',
      slug: 'deep9-slim-shoes',
      category: 'shoes',
      image: '/images/shoes/shoes9.jpeg',
      price: 900,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
    {
      name: 'deep10 shoes',
      slug: 'deep10-slim-shoes',
      category: 'shoes',
      image: '/images/shoes/shoes10.jpeg',
      price: 1000,
      CountInStock: 10,
      brand: 'nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high qulity shirt',
    },
  ],
};
export default data;
